export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = " CLEAR_ALERT";
export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";
export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_VALUES = "CLEAR_VALUES";

export const CREATE_JOB_BEGIN = "CREATE_JOB_BEGIN";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_ERROR = "CREATE_JOB_ERROR";

export const GET_JOBS_BEGIN = "GET_JOBS_BEGIN";
export const GET_JOBS_SUCCESS = "GET_JOBS_SUCCESS";

export const SET_EDIT_JOB = "SET_EDIT_JOB";

export const DELETE_JOB_BEGIN = "DELETE_JOB_BEGIN";

export const EDIT_JOB_BEGIN = "EDIT_JOB_BEGIN";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_ERROR = "EDIT_JOB_ERROR";

// HRMS ACTION

export const CREATE_DETAIL_BEGIN = "CREATE_DETAIL_BEGIN";
export const CREATE_DETAIL_SUCCESS = "CREATE_DETAIL_SUCCESS";
export const CREATE_DETAIL_ERROR = "CREATE_DETAIL_ERROR";

export const GET_DETAIL_BEGIN = "GET_DETAIL_BEGIN";
export const GET_DETAIL_SUCCESS = "GET_DETAIL_SUCCESS";

export const DELETE_DETAIL_BEGIN = "DELETE_DETAIL_BEGIN";

export const SET_EDIT_DETAIL = "SET_EDIT_DETAIL";

export const EDIT_DETAIL_BEGIN = "EDIT_DETAIL_BEGIN";
export const EDIT_DETAIL_SUCCESS = "EDIT_DETAIL_SUCCESS";
export const EDIT_DETAIL_ERROR = "EDIT_DETAIL_ERROR";
//  department details in future for  all dynamic approch
export const CREATE_DEPARTMENT_BEGIN = "CREATE_DEPARTMENT_BEGIN";
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const CREATE_DEPARTMENT_ERROR = "CREATE_DEPARTMENT_ERROR";

export const GET_DEPARTMENT_BEGIN = "GET_DEPARTMENT_BEGIN";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";

export const SET_EDIT_DEPARTMENT = "SET_EDIT_DEPARTMENTS";

export const EDIT_DEPARTMENT_BEGIN = "EDIT_DEPARTMENT_BEGIN";
export const EDIT_DEPARTMENT_SUCCESS = "EDIT_DEPARTMENT_SUCCESS";
export const EDIT_DEPARTMENT_ERROR = "EDIT_DEPARTMENT_ERROR";

export const SET_PENDING = "SET_PENDING";

export const GET_CALENDAR_BEGIN = "GET_CALENDAR_BEGIN";
export const GET_CALENDAR_SUCCESS = "GET_CALENDAR_SUCCESS";

export const PUNCHIN_BEGIN = "PUNCHIN_BEGIN";
export const PUNCHIN_SUCCESS = "PUNCHIN_SUCCESS";
export const PUNCHIN_ERROR = "PUNCHIN_ERROR";

export const PUNCHOUT_BEGIN = "PUNCHOUT_BEGIN";
export const PUNCHOUT_SUCCESS = "PUNCHOUT_SUCCESS";
export const PUNCHOUT_ERROR = "PUNCHOUT_ERROR";

export const CLEAR_FILTERS = "CLEAR_FILTERS";

export const CHANGE_PAGE = "CHANGE_PAGE";

export const REGISTER_NEW_USER_ADMIN_BEGIN = "REGISTER_NEW_USER_ADMIN_BEGIN";
export const REGISTER_NEW_USER_ADMIN_SUCCESS =
  "REGISTER_NEW_USER_ADMIN_SUCCESS";
export const REGISTER_NEW_USER_ADMIN_ERROR = "REGISTER_NEW_USER_ADMIN_ERROR";

export const GET_PRESANT = "GET_PRESANT";
export const GET_PRESANT_SUCCESS = "GET_PRESANT_SUCCESS";

export const GET_ABSENT = "GET_ABSENT";
export const GET_PRESANT_ABSENT = "GET_PRESANT_ABSENT";

export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";

export const CREATE_LOCATION_SUCCESS = "CREATE_LOCATION_SUCCESS";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";

export const CREATE_DEPARTMENTOPTION_SUCCESS =
  "CREATE_DEPARTMENTOPTION_SUCCESS";
export const GET_DEPARTMENTOPTION_SUCCESS = "GET_DEPARTMENTOPTION_SUCCESS";

export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";

export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";


export const GET_EMPLOYEEDASHBOARD = 'GET_EMPLOYEEDASHBOARD '
export const GET_EMPLOYEEDASHBOARD_ERROR = 'GET_EMPLOYEEDASHBOARD_ERROR '